/*	Problem 45
	Triangular, Pentagonal, and Hexagonal

	Triangle, pentagonal, and hexagonal numbers are generated by the following
	formulae:

	Triangle	 	Tn = n(n+1)/2	 	1, 3, 6, 10, 15, ...
	Pentagonal	 	Pn = n(3n−1)/2	 	1, 5, 12, 22, 35, ...
	Hexagonal	 	Hn = n(2n−1)	 	1, 6, 15, 28, 45, ...

	It can be verified that T285 = P165 = H143 = 40755.

	Find the next triangle number that is also pentagonal and hexagonal.
*/

#include <cmath>
#include <iomanip>
#include <iostream>

using namespace std;

double getTriNum (double n) {
	return (n * (n + 1)) / 2;
}

bool isTriangular (double n) {
	double val = (sqrt ((8 * n) + 1) - 1) / 2;
	if (val == int (val)) {
		return true;
	}
	return false;
}

bool isPentagonal (double n) {
	double val = (sqrt ((24 * n) + 1) + 1) / 6;
	if (val == int (val)) {
		return true;
	}
	return false;
}

bool isHexagonal (double n) {
	double val = (sqrt ((8 * n) + 1) + 1) / 4;
	if (val == int (val)) {
		return true;
	}
	return false;
}

bool isTriPentHex (double n) {
	return (isTriangular (n) && isPentagonal (n) && isHexagonal (n));
}

int main () {
	int n = 286;
	cout << setprecision (0) << fixed;

	while (!isTriPentHex (getTriNum (double (n)))) {
		n++;
	}

	cout << getTriNum (n) << endl;
}